[theme]
base = "light"
primaryColor = "#087F7B"
backgroundColor = "#F5F7F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#17212B"
font = "sans-serif"
baseRadius = "6px"

[server]
headless = true
maxUploadSize = 500
address = "127.0.0.1"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
